export const advanced = [
  {
    id: 1,
    text: "exhilarating adventure uncharted territories vast planet intrepid explorers perilous journeys treacherous terrain unpredictable weather conditions allure discovery propels forward hearts pounding anticipation uncover hidden wonders majestic mountains distance snow capped peaks piercing clouds dense jungles teem exotic flora fauna offering symphony sights sounds venture within mysterious caves beckon promising secrets forgotten time sun sets casting golden glow across landscape weary travelers camp sharing tales experiences around crackling campfires night sky reveals tapestry stars reminding place universe each new dawn comes renewed determination push further learn embrace unknown courageous individuals inspire step outside comfort zones seek extraordinary stories triumph over adversity remind indomitable human spirit capacity greatness technology advances new frontiers open offering opportunities exploration discovery depths oceans farthest reaches space always something new uncover another mystery solve pursuit knowledge drives forward fueling curiosity igniting passion adventure brave explorers continue push boundaries expanding horizons inspiring generations come follow footsteps quest understanding world around never ending journey filled wonder excitement possibility awaits those dare take first step into unknown realms beyond imagination await discovery intrepid souls willing venture forth"
  },
  {
    id: 2,
    text: "intricate world quantum mechanics continues baffle fascinate scientists laypeople alike subatomic particles behave ways defy classical understanding physics exhibiting properties superposition entanglement researchers tirelessly work unravel mysteries conducting experiments push boundaries knowledge quantum computers once thought purely theoretical now becoming reality promising revolutionize fields cryptography drug discovery concept parallel universes once relegated realm science fiction now seriously considered physicists possible explanation quantum phenomena understanding quantum world grows ability harness power practical applications ultra precise atomic clocks quantum sensors capable detecting tiniest fluctuations gravitational fields potential applications seem limitless progress only scratched surface quantum mechanics may reveal nature reality itself quest unified theory everything continues driving physicists explore ever more esoteric concepts mathematical models delve deeper quantum realm forced confront fundamental questions nature consciousness free will very fabric spacetime itself quantum entanglement spooky action distance einstein famously described continues perplex scientists offering tantalizing glimpses underlying structure universe quantum tunneling allows particles pass through seemingly impenetrable barriers defying classical logic quantum superposition suggests particles exist multiple states simultaneously until observed measured implications quantum mechanics extend beyond realm subatomic reaching into macroscopic world around us"
  },
  {
    id: 3,
    text: "culinary world vibrant tapestry flavors textures aromas tantalize senses nourish bodies passionate chefs dedicate lives mastering art gastronomy experimenting innovative techniques unexpected ingredient combinations bustling street markets southeast asia michelin starred restaurants europe food serves universal language brings people together farm table movement gained momentum emphasizing importance locally sourced seasonal ingredients molecular gastronomy pushes boundaries traditional cooking using scientific principles create mind bending culinary experiences fusion cuisine blends elements different culinary traditions resulting exciting new flavor profiles challenge preconceptions global awareness environmental issues grows sustainable cooking practices becoming increasingly important chefs finding creative ways reduce food waste utilize overlooked ingredients promote biodiversity through menus rise plant based diets sparked revolution vegetarian vegan cuisine proving delicious satisfying meals created without animal products culinary tourism become popular way travelers experience different cultures food tours cooking classes offering immersive experiences continue explore vast world gastronomy discover not only new flavors also new ways connecting each other world around us gastronomic adventures await those willing expand palates embrace unfamiliar cuisines each dish tells story culture history people who created passed down through generations"
  },
  {
    id: 4,
    text: "realm artificial intelligence continues evolve astonishing pace transforming industries reshaping daily lives machine learning algorithms grow increasingly sophisticated capable recognizing patterns making decisions remarkable accuracy natural language processing enables computers understand generate human like text opening new possibilities communication information retrieval computer vision systems now interpret analyze visual data superhuman precision revolutionizing fields medical imaging autonomous vehicles ai systems become advanced ethical considerations come forefront sparking debates privacy accountability potential bias algorithmic decision making concept artificial general intelligence system capable performing any intellectual task human can do remains elusive goal continues drive research speculation neuromorphic computing inspired structure function human brain promises create more efficient adaptable ai systems integration ai into robotics leading development increasingly capable versatile machines industrial automation personal assistants navigate rapidly changing landscape becomes crucial consider societal implications widespread ai adoption ensure powerful tools used responsibly benefit humanity deep learning neural networks mimic structure human brain allowing ai systems learn vast amounts data without explicit programming reinforcement learning enables ai agents learn through trial error improving performance over time edge computing brings ai capabilities closer end users reducing latency improving privacy federated learning allows ai models trained across multiple devices without sharing raw data"
  },
  {
    id: 5,
    text: "intricate world neuroscience continues unveil mysteries human brain offering unprecedented insights cognition emotion consciousness advanced neuroimaging techniques allow researchers observe brain activity real time mapping complex networks underlie thoughts behaviors study neuroplasticity reveals brain remarkable ability adapt rewire itself response new experiences challenges neuroscientists explore mechanisms memory formation retrieval shedding light conditions alzheimer disease offering hope new treatments field neuroethics grapples philosophical moral implications growing ability manipulate brain function research neural correlates consciousness seeks unravel one greatest mysteries science how subjective experience arises physical matter emerging field optogenetics allows scientists control specific neurons light offering new ways study brain function potentially treat neurological disorders advances brain computer interfaces promise restore mobility communication those severe disabilities understanding brain grows appreciation incredible complexity myriad ways shapes perception reality sense self neurotransmitters chemical messengers brain play crucial role regulating mood behavior learning memory neurogenesis formation new neurons continues throughout life challenging long held beliefs brain structure epigenetics studies how environmental factors can influence gene expression affecting brain function behavior neurodegenerative diseases alzheimer parkinson huntington continue challenge researchers seeking understand underlying mechanisms develop effective treatments"
  },
  {
    id: 6,
    text: "captivating world marine biology reveals astonishing diversity resilience life beneath waves oceanographers explore vast underwater ecosystems vibrant coral reefs teeming colorful fish mysterious depths abyssal zone bioluminescent organisms create spectacular light shows darkest reaches ocean glow serving various purposes communication predation marine mammals whales dolphins exhibit complex social behaviors communication systems continue fascinate researchers study marine microorganisms unveils crucial role global nutrient cycles climate regulation conservation efforts focus protecting endangered species preserving delicate marine habitats threatened human activity climate change advances underwater technology allow scientists explore previously inaccessible areas leading discovery new species ecosystems field marine biotechnology harnesses unique properties marine organisms develop new medicines materials delve deeper mysteries ocean gain greater appreciation interconnectedness all life earth vital importance preserving planet aquatic environments future generations hydrothermal vents deep sea floor support unique ecosystems thriving extreme conditions offering insights potential life other planets coral reefs often called rainforests sea harbor incredible biodiversity provide crucial habitat countless marine species phytoplankton microscopic marine plants produce half world oxygen play vital role global carbon cycle marine mammals exhibit remarkable adaptations deep diving long distance migration complex social structures"
  },
  {
    id: 7,
    text: "fascinating field archaeology continues unearth secrets ancient civilizations providing valuable insights human history cultural evolution advanced technologies ground penetrating radar lidar allow archaeologists discover hidden structures artifacts without disturbing site careful excavation techniques reveal layers history each telling unique story people lived there study ancient dna provides unprecedented information human migration patterns genetic diversity throughout history underwater archaeology explores sunken cities shipwrecks offering glimpses maritime trade naval warfare past preservation restoration ancient artifacts require meticulous attention detail specialized knowledge materials science digital reconstruction techniques allow researchers visualize ancient sites artifacts original form bringing history life field archaeoastronomy examines how ancient cultures understood used celestial phenomena revealing sophisticated astronomical knowledge piece together puzzle human history gain deeper understanding shared heritage diverse ways societies adapted environments over time ongoing work archaeologists not only illuminates past also provides valuable context understanding contemporary cultural social issues paleoanthropology study human evolution fossil record sheds light origins development homo sapiens related species experimental archaeology involves recreating ancient technologies practices better understand how people lived worked past times dendrochronology uses tree ring patterns date archaeological finds providing precise chronologies ancient civilizations"
  },
  {
    id: 8,
    text: "dynamic world renewable energy continues evolve offering promising solutions global challenge climate change solar photovoltaic technology becomes increasingly efficient affordable making clean electricity accessible more people around world wind turbines grow larger powerful harnessing energy offshore breezes power coastal communities advances energy storage systems grid scale batteries pumped hydro storage help overcome intermittency issues associated renewable sources geothermal energy taps earth internal heat providing constant reliable source clean power development advanced biofuels offers sustainable alternatives fossil fuels transportation industry wave tidal energy systems harness power oceans although challenges remain scaling technologies concept smart grid capable efficiently managing distributing energy multiple renewable sources becoming reality many parts world renewable energy technologies continue improve costs decrease transition clean energy future becomes increasingly feasible growth renewable energy sector not only addresses environmental concerns also creates new economic opportunities improves energy security nations around globe concentrated solar power uses mirrors lenses focus sunlight generate electricity heat hydrogen fuel cells offer clean efficient way store transport energy potential applications ranging vehicles stationary power systems biomass energy utilizes organic matter source renewable fuel helping reduce waste providing alternative fossil fuels"
  },
  {
    id: 9,
    text: "intricate world cryptography plays crucial role securing digital lives protecting sensitive information modern encryption algorithms use complex mathematical principles render data unreadable unauthorized parties development quantum cryptography promises create unbreakable codes leveraging principles quantum mechanics blockchain technology built cryptographic principles offers new paradigms secure transparent record keeping field steganography explores methods hiding secret messages within seemingly innocuous data adding another layer security cryptanalysts work tirelessly identify vulnerabilities encryption systems helping strengthen cybersecurity measures ongoing debate over encryption backdoors highlights tension between privacy rights law enforcement needs artificial intelligence advances new challenges opportunities arise realm cryptography including ai assisted code breaking development ai resistant encryption methods history cryptography filled fascinating stories code makers code breakers whose work often played decisive role shaping world events lives become increasingly digital importance robust cryptographic systems protecting privacy security cannot overstated public key cryptography allows secure communication over insecure channels revolutionizing online transactions digital signatures homomorphic encryption enables computations encrypted data without decrypting offering new possibilities cloud computing data analysis while maintaining privacy zero knowledge proofs allow one party prove knowledge information without revealing information itself"
  },
  {
    id: 10,
    text: "captivating world astrophysics continues expand understanding cosmos place within powerful telescopes peer depths space revealing distant galaxies echoes big bang search exoplanets yields exciting discoveries raising possibility finding life beyond earth study dark matter dark energy challenges fundamental understanding universe composition evolution gravitational wave astronomy opens new window cosmos allowing detect cataclysmic events like merging black holes field astrobiology explores potential life extreme environments both earth other celestial bodies advances space propulsion technology bring closer dream interplanetary travel colonization other worlds study stellar evolution provides insights life cycles stars origin elements make world unravel mysteries universe gain deeper appreciation vastness complexity cosmos ongoing exploration space not only satisfies innate curiosity also drives technological innovation inspires push boundaries human knowledge achievement cosmic microwave background radiation provides glimpse earliest moments universe offering clues its origin evolution study gamma ray bursts most energetic explosions universe sheds light extreme physics stellar deaths formation black holes search technosignatures signs advanced extraterrestrial civilizations expands traditional search extraterrestrial intelligence include potential artifacts megastructures"
  }
]